postgresql: &postgresql
  adapter: postgresql
  host: localhost
  pool: 5
  timeout: 5000
  username: postgres
  password: 21335581

development:
  <<: *postgresql
  database: SysTTA_development

test:
  <<: *postgresql
  database: SysTTA_test

production:
  <<: *postgresql
  database: SysTTA_production
